app.name=GameVault
app.version=1.0.0
database.url=jdbc:sqlite:data/gamevault.db
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
figma.library=https://www.figma.com/design/ec8xxk2sc2PyamQ9Ai7NDa/ProjetDevDesktop?node-id=0-152&m=dev
figma.add=https://www.figma.com/design/ec8xxk2sc2PyamQ9Ai7NDa/ProjetDevDesktop?node-id=0-3&m=dev
figma.detail=https://www.figma.com/design/ec8xxk2sc2PyamQ9Ai7NDa/ProjetDevDesktop?node-id=0-401&m=dev
figma.statistics=https://www.figma.com/design/ec8xxk2sc2PyamQ9Ai7NDa/ProjetDevDesktop?node-id=0-614&m=dev
figma.settings=https://www.figma.com/design/ec8xxk2sc2PyamQ9Ai7NDa/ProjetDevDesktop?node-id=1-13&m=dev
figma.profile=https://www.figma.com/design/ec8xxk2sc2PyamQ9Ai7NDa/ProjetDevDesktop?node-id=1-195&m=dev
